-- --------------------------------------------------------
-- 호스트:                          52.89.91.108
-- 서버 버전:                        5.5.46 - MySQL Community Server (GPL)
-- 서버 OS:                        Linux
-- HeidiSQL 버전:                  8.0.0.4396
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- SMART_MESSAGE 의 데이터베이스 구조 덤핑
CREATE DATABASE IF NOT EXISTS `SMART_MESSAGE` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `SMART_MESSAGE`;


-- 테이블 SMART_MESSAGE의 구조를 덤프합니다. EM_MMT_LOG_201601
DROP TABLE IF EXISTS `EM_MMT_LOG_201601`;
CREATE TABLE IF NOT EXISTS `EM_MMT_LOG_201601` (
  `MT_PR` int(11) NOT NULL,
  `MT_SEQ` int(11) NOT NULL,
  `MT_REFKEY` varchar(20) DEFAULT NULL,
  `PRIORITY` char(2) NOT NULL DEFAULT 'S',
  `MSG_CLASS` char(1) DEFAULT '1',
  `DATE_CLIENT_REQ` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `SUBJECT` varchar(40) NOT NULL,
  `CONTENT_TYPE` int(11) DEFAULT '0',
  `CONTENT` varchar(4000) NOT NULL,
  `ATTACH_FILE_GROUP_KEY` int(11) DEFAULT '0',
  `CALLBACK` varchar(25) NOT NULL,
  `SERVICE_TYPE` char(2) NOT NULL,
  `BROADCAST_YN` char(1) NOT NULL DEFAULT 'N',
  `MSG_STATUS` char(1) NOT NULL DEFAULT '1',
  `RECIPIENT_NUM` varchar(25) DEFAULT NULL,
  `CHANGE_WORD1` varchar(20) DEFAULT NULL,
  `CHANGE_WORD2` varchar(20) DEFAULT NULL,
  `CHANGE_WORD3` varchar(20) DEFAULT NULL,
  `CHANGE_WORD4` varchar(20) DEFAULT NULL,
  `CHANGE_WORD5` varchar(20) DEFAULT NULL,
  `DATE_MT_SENT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `DATE_RSLT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `DATE_MT_REPORT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MT_REPORT_CODE_IB` char(4) DEFAULT NULL,
  `MT_REPORT_CODE_IBTYPE` char(1) DEFAULT NULL,
  `CARRIER` int(11) DEFAULT NULL,
  `RS_ID` varchar(20) DEFAULT NULL,
  `RECIPIENT_NET` int(11) DEFAULT NULL,
  `RECIPIENT_NPSEND` char(1) DEFAULT NULL,
  `COUNTRY_CODE` varchar(8) NOT NULL DEFAULT '82',
  `CHARSET` varchar(20) DEFAULT NULL,
  `MSG_TYPE` int(11) DEFAULT NULL,
  `CRYPTO_YN` char(1) DEFAULT 'Y',
  `TTL` int(11) DEFAULT NULL,
  `ATA_ID` char(2) DEFAULT '',
  `REG_DATE_TRAN` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `REG_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MT_RES_CNT` int(11) DEFAULT NULL,
  `SENDER_KEY` varchar(40) NOT NULL,
  `TEMPLATE_CODE` varchar(10) NOT NULL,
  `ETC_TEXT_1` varchar(100) DEFAULT NULL,
  `ETC_TEXT_2` varchar(100) DEFAULT NULL,
  `ETC_TEXT_3` varchar(100) DEFAULT NULL,
  `ETC_NUM_1` int(11) DEFAULT NULL,
  `ETC_NUM_2` int(11) DEFAULT NULL,
  `ETC_NUM_3` int(11) DEFAULT NULL,
  `ETC_DATE_1` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.


-- 테이블 SMART_MESSAGE의 구조를 덤프합니다. EM_MMT_LOG_201602
DROP TABLE IF EXISTS `EM_MMT_LOG_201602`;
CREATE TABLE IF NOT EXISTS `EM_MMT_LOG_201602` (
  `MT_PR` int(11) NOT NULL,
  `MT_SEQ` int(11) NOT NULL,
  `MT_REFKEY` varchar(20) DEFAULT NULL,
  `PRIORITY` char(2) NOT NULL DEFAULT 'S',
  `MSG_CLASS` char(1) DEFAULT '1',
  `DATE_CLIENT_REQ` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `SUBJECT` varchar(40) NOT NULL,
  `CONTENT_TYPE` int(11) DEFAULT '0',
  `CONTENT` varchar(4000) NOT NULL,
  `ATTACH_FILE_GROUP_KEY` int(11) DEFAULT '0',
  `CALLBACK` varchar(25) NOT NULL,
  `SERVICE_TYPE` char(2) NOT NULL,
  `BROADCAST_YN` char(1) NOT NULL DEFAULT 'N',
  `MSG_STATUS` char(1) NOT NULL DEFAULT '1',
  `RECIPIENT_NUM` varchar(25) DEFAULT NULL,
  `CHANGE_WORD1` varchar(20) DEFAULT NULL,
  `CHANGE_WORD2` varchar(20) DEFAULT NULL,
  `CHANGE_WORD3` varchar(20) DEFAULT NULL,
  `CHANGE_WORD4` varchar(20) DEFAULT NULL,
  `CHANGE_WORD5` varchar(20) DEFAULT NULL,
  `DATE_MT_SENT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `DATE_RSLT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `DATE_MT_REPORT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MT_REPORT_CODE_IB` char(4) DEFAULT NULL,
  `MT_REPORT_CODE_IBTYPE` char(1) DEFAULT NULL,
  `CARRIER` int(11) DEFAULT NULL,
  `RS_ID` varchar(20) DEFAULT NULL,
  `RECIPIENT_NET` int(11) DEFAULT NULL,
  `RECIPIENT_NPSEND` char(1) DEFAULT NULL,
  `COUNTRY_CODE` varchar(8) NOT NULL DEFAULT '82',
  `CHARSET` varchar(20) DEFAULT NULL,
  `MSG_TYPE` int(11) DEFAULT NULL,
  `CRYPTO_YN` char(1) DEFAULT 'Y',
  `TTL` int(11) DEFAULT NULL,
  `ATA_ID` char(2) DEFAULT '',
  `REG_DATE_TRAN` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `REG_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MT_RES_CNT` int(11) DEFAULT NULL,
  `SENDER_KEY` varchar(40) NOT NULL,
  `TEMPLATE_CODE` varchar(10) NOT NULL,
  `ETC_TEXT_1` varchar(100) DEFAULT NULL,
  `ETC_TEXT_2` varchar(100) DEFAULT NULL,
  `ETC_TEXT_3` varchar(100) DEFAULT NULL,
  `ETC_NUM_1` int(11) DEFAULT NULL,
  `ETC_NUM_2` int(11) DEFAULT NULL,
  `ETC_NUM_3` int(11) DEFAULT NULL,
  `ETC_DATE_1` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- 테이블 SMART_MESSAGE의 구조를 덤프합니다. EM_MMT_LOG_201602
DROP TABLE IF EXISTS `EM_MMT_LOG_201603`;

CREATE TABLE IF NOT EXISTS `EM_MMT_LOG_201603` (
  `MT_PR` int(11) NOT NULL,
  `MT_SEQ` int(11) NOT NULL,
  `MT_REFKEY` varchar(20) DEFAULT NULL,
  `PRIORITY` char(2) NOT NULL DEFAULT 'S',
  `MSG_CLASS` char(1) DEFAULT '1',
  `DATE_CLIENT_REQ` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `SUBJECT` varchar(40) NOT NULL,
  `CONTENT_TYPE` int(11) DEFAULT '0',
  `CONTENT` varchar(4000) NOT NULL,
  `ATTACH_FILE_GROUP_KEY` int(11) DEFAULT '0',
  `CALLBACK` varchar(25) NOT NULL,
  `SERVICE_TYPE` char(2) NOT NULL,
  `BROADCAST_YN` char(1) NOT NULL DEFAULT 'N',
  `MSG_STATUS` char(1) NOT NULL DEFAULT '1',
  `RECIPIENT_NUM` varchar(25) DEFAULT NULL,
  `CHANGE_WORD1` varchar(20) DEFAULT NULL,
  `CHANGE_WORD2` varchar(20) DEFAULT NULL,
  `CHANGE_WORD3` varchar(20) DEFAULT NULL,
  `CHANGE_WORD4` varchar(20) DEFAULT NULL,
  `CHANGE_WORD5` varchar(20) DEFAULT NULL,
  `DATE_MT_SENT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `DATE_RSLT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `DATE_MT_REPORT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MT_REPORT_CODE_IB` char(4) DEFAULT NULL,
  `MT_REPORT_CODE_IBTYPE` char(1) DEFAULT NULL,
  `CARRIER` int(11) DEFAULT NULL,
  `RS_ID` varchar(20) DEFAULT NULL,
  `RECIPIENT_NET` int(11) DEFAULT NULL,
  `RECIPIENT_NPSEND` char(1) DEFAULT NULL,
  `COUNTRY_CODE` varchar(8) NOT NULL DEFAULT '82',
  `CHARSET` varchar(20) DEFAULT NULL,
  `MSG_TYPE` int(11) DEFAULT NULL,
  `CRYPTO_YN` char(1) DEFAULT 'Y',
  `TTL` int(11) DEFAULT NULL,
  `ATA_ID` char(2) DEFAULT '',
  `REG_DATE_TRAN` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `REG_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MT_RES_CNT` int(11) DEFAULT NULL,
  `SENDER_KEY` varchar(40) NOT NULL,
  `TEMPLATE_CODE` varchar(10) NOT NULL,
  `ETC_TEXT_1` varchar(100) DEFAULT NULL,
  `ETC_TEXT_2` varchar(100) DEFAULT NULL,
  `ETC_TEXT_3` varchar(100) DEFAULT NULL,
  `ETC_NUM_1` int(11) DEFAULT NULL,
  `ETC_NUM_2` int(11) DEFAULT NULL,
  `ETC_NUM_3` int(11) DEFAULT NULL,
  `ETC_DATE_1` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- 내보낼 데이터가 선택되어 있지 않습니다.


-- 테이블 SMART_MESSAGE의 구조를 덤프합니다. EM_MMT_TRAN
DROP TABLE IF EXISTS `EM_MMT_TRAN`;
CREATE TABLE IF NOT EXISTS `EM_MMT_TRAN` (
  `MT_PR` int(11) NOT NULL,
  `MT_REFKEY` varchar(20) DEFAULT NULL,
  `PRIORITY` char(2) NOT NULL DEFAULT 'S',
  `MSG_CLASS` char(1) DEFAULT '1',
  `DATE_CLIENT_REQ` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `SUBJECT` varchar(40) NOT NULL,
  `CONTENT_TYPE` int(11) DEFAULT '0',
  `CONTENT` varchar(4000) NOT NULL,
  `ATTACH_FILE_GROUP_KEY` int(11) DEFAULT '0',
  `CALLBACK` varchar(25) NOT NULL,
  `SERVICE_TYPE` char(2) NOT NULL DEFAULT '3',
  `BROADCAST_YN` char(1) NOT NULL DEFAULT 'N',
  `MSG_STATUS` char(1) NOT NULL DEFAULT '1',
  `RECIPIENT_NUM` varchar(25) DEFAULT NULL,
  `DATE_MT_SENT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `DATE_RSLT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `DATE_MT_REPORT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MT_REPORT_CODE_IB` char(4) DEFAULT NULL,
  `MT_REPORT_CODE_IBTYPE` char(1) DEFAULT NULL,
  `CARRIER` int(11) DEFAULT NULL,
  `RS_ID` varchar(20) DEFAULT NULL,
  `RECIPIENT_NET` int(11) DEFAULT NULL,
  `RECIPIENT_NPSEND` char(1) DEFAULT NULL,
  `COUNTRY_CODE` varchar(8) NOT NULL DEFAULT '82',
  `CHARSET` varchar(20) DEFAULT NULL,
  `MSG_TYPE` int(11) NOT NULL DEFAULT '1008',
  `CRYPTO_YN` char(1) DEFAULT 'Y',
  `TTL` int(11) DEFAULT NULL,
  `ATA_ID` char(2) DEFAULT '',
  `REG_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MT_RES_CNT` int(11) DEFAULT NULL,
  `SENDER_KEY` varchar(40) NOT NULL,
  `TEMPLATE_CODE` varchar(10) NOT NULL,
  `ETC_TEXT_1` varchar(100) DEFAULT NULL,
  `ETC_TEXT_2` varchar(100) DEFAULT NULL,
  `ETC_TEXT_3` varchar(100) DEFAULT NULL,
  `ETC_NUM_1` int(11) DEFAULT NULL,
  `ETC_NUM_2` int(11) DEFAULT NULL,
  `ETC_NUM_3` int(11) DEFAULT NULL,
  `ETC_DATE_1` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.


-- 테이블 SMART_MESSAGE의 구조를 덤프합니다. SMART_AGENT_INFO
DROP TABLE IF EXISTS `SMART_AGENT_INFO`;
CREATE TABLE IF NOT EXISTS `SMART_AGENT_INFO` (
  `AIDX` varchar(20) NOT NULL,
  `NAME` varchar(20) DEFAULT NULL,
  `PASSWD` varchar(50) DEFAULT NULL,
  `PHONE` varchar(15) DEFAULT NULL,
  `CP_ID` varchar(10) DEFAULT NULL, /* 미사용 */
  `CIDX` varchar(36) DEFAULT NULL,
  `AUTH` varchar(10) DEFAULT NULL, /* 마스터 : M(전체권한), 문구 등록만 가능 : W, 이력관리만 가능 : H, 문구등록, 이력관리 가능 : A */
  `REG_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`AIDX`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- 테이블 SMART_MESSAGE의 구조를 덤프합니다. SMART_AGENT_INFO
DROP TABLE IF EXISTS `SMART_COMPANY_INFO`;
CREATE TABLE IF NOT EXISTS  `SMART_COMPANY_INFO` (
  `CIDX` varchar(36) NOT NULL,
  `NAME` varchar(64) DEFAULT NULL,
  `PHONE` varchar(15) DEFAULT NULL,
  `AUTH_KEY` varchar(128) DEFAULT NULL,
  `REG_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CIDX`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
-- 내보낼 데이터가 선택되어 있지 않습니다.


-- 테이블 SMART_MESSAGE의 구조를 덤프합니다. SMART_MESSAGE_ERRCODE
DROP TABLE IF EXISTS `SMART_MESSAGE_ERRCODE`;
CREATE TABLE IF NOT EXISTS `SMART_MESSAGE_ERRCODE` (
  `IDX` int(11) NOT NULL AUTO_INCREMENT,
  `MTYPE` varchar(4) DEFAULT NULL,
  `CODE` varchar(50) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `REG_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`IDX`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (1,'A','1000','성공',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (2,'A','2000','전송 시간 초과',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (3,'A','2001','메시지 전송 불가 (예기치 않은 오류 발생)',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (4,'A','3009','메시지 형식 오류',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (5,'A','3014','알 수 없는 메시지 상태',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (6,'A','3021','카카오톡을 사용하지 않는 사용자',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (7,'A','3022','알림톡 차단을 선택한 사용자',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (8,'A','3023','메시지 문법 오류',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (9,'A','3024','발신 프로필 키가 유효하지 않음',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (10,'A','3025','메시지 전송 실패 (테스트 시, 친구관계가 아닌 경우)',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (11,'A','3026','메시지와 템플릿의 일치성 확인시 오류 발생',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (12,'A','3027','카카오톡을 사용하지 않는 사용자 (전화번호 오류)',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (13,'A','3028','카카오톡을 사용하지 않는 사용자 (050 안심번호)',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (14,'A','3029','메시지가 존재하지 않음',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (15,'A','3030','메시지 일련번호가 중복됨',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (16,'A','3031','메시지가 비어 있음',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (17,'A','3032','메시지 길이 제한 오류 (공백 포함 1000 자)',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (18,'A','3033','템플릿을 찾을 수 없음',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (19,'A','3034','메시지가 템플릿과 일치하지 않음',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (20,'A','3035','5 초 이내에 메시지를 중복 발송',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (21,'A','3036','72시간 이내에 카카오톡 사용 이력이 없는 사용자',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (22,'A','1001','Server Busy (RS 내부 저장 Queue Full)',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (23,'A','1002','수신번호 형식 오류',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (24,'A','1003','회신번호 형식 오류',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (25,'A','1009','CLIENT_MSG_KEY 없음',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (26,'A','1010','CONTENT 없음',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (27,'A','1012','RECIPIENT_INFO 없음',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (28,'A','1013','SUBJECT 없음',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (29,'A','1018','전송 권한 없음',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (30,'A','1019','TTL 초과',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (31,'A','1020','charset conversion error',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (32,'A','1099','인증 실패',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (33,'A','E901','수신번호가 없는 경우',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (34,'A','E903','제목 없는 경우',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (35,'A','E904','메시지가 없는 경우',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (36,'A','E905','회신번호가 없는 경우',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (37,'A','E906','메시지키가 없는 경우',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (38,'A','E915','중복메시지',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (39,'A','E916','인증서버 차단번호',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (40,'A','E917','고객DB 차단번호',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (41,'A','E918','USER CALLBACK FAIL',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (42,'A','E919','발송 제한 시간인 경우, 메시지 재발송 처리가 금지 된 경우',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (43,'A','E920','서비스 타입이 알림톡인 경우, 메시지 테이블에 파일그룹키가 있는 경우',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (44,'A','E999','기타오류',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (45,'L','1000','성공',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (46,'L','6601','타임 아웃',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (47,'L','6602','핸드폰 호 처리 중',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (48,'L','6603','음영 지역',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (49,'L','6604','전원이 꺼져 있음',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (50,'L','6605','메시지 저장개수 초과',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (51,'L','6606','잘못된 번호',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (52,'L','6607','서비스 일시 정지',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (53,'L','6608','기타 단말기 문제',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (54,'L','6609','착신 거절',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (56,'L','6611','통신사의 SMC 형식 오류',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (57,'L','6612','게이트웨이의 형식 오류',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (58,'L','6613','서비스 불가 단말기',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (59,'L','6614','핸드폰 호 불가 상태',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (60,'L','6615','SMC 운영자에 의해 삭제',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (61,'L','6616','통신사의 메시지 큐 초과',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (62,'L','6617','통신사의 스팸 처리',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (63,'L','6618','공정위의 스팸 처리',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (64,'L','6619','게이트웨이의 스팸 처리',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (65,'L','6620','발송 건수 초과',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (66,'L','6621','메시지의 길이 초과',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (67,'L','6622','잘못된 번호 형식',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (68,'L','6623','잘못된 데이터 형식',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (69,'L','6624','MMS 정보를 찾을 수 없음',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (70,'L','6625','NPDB에러',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (71,'L','6626','080 수신거부(SPAM)',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (72,'L','6627','발송제한 수신거부(SPAM)',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (73,'L','6628','회신번호 차단(개인)',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (74,'L','6629','회신번호 차단(기업)',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (75,'L','6630','서비스 불가 번호',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (76,'L','6670','첨부파일 사이즈 초과(60K)',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (77,'L','9903','선불사용자 사용금지',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (78,'L','9904','Block time ( 날짜제한 )',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (79,'L','9081','선불 사용자 FAX, PHONE 발송 제한',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (80,'L','9082','발송해제',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (81,'L','9083','IP차단',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (82,'L','9084','DEVICE 발송 제한',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (83,'L','9085','사용금지 Callback 번호',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (84,'L','9023','Callback error',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (85,'L','9905','Block time ( 요일제한 )',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (86,'L','9010','아이디틀림',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (87,'L','9011','비밀번호 틀림',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (88,'L','9012','중복접속량 많음',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (89,'L','9013','발송시간 지난 데이터',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (90,'L','9014','시간제한 (리포트 수신대기timeout)',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (91,'L','9020','Wrong Data Format',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (92,'L','9021','Wrong Data Format',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (93,'L','9022','Wrong Data Format (cinfo가 특수 문자 / , 공백 을 포함하고 있다)',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (94,'L','9080','Deny User Ack 9214 Wrong Phone Num',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (95,'L','9311','Fax File Not Found 9908 PHONE,FAX선불사용자 제한기능',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (97,'L','-1','잘못된 데이터 형식 클라이언트단 발송 오류',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (98,'L','9090','기타에러(정리된실패사유 이외에 명확하지않은 예외 상황에서 발생될 수 있는 에러로 명확한 사유 확인을 위해서는 별도의 확인 진행필요.)',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (99,'N','N1001','가입되지않은 사용자',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (100,'N','N1002','파라미터 값 에러',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (101,'N','N1003','기타 에러',NOW());
Insert into SMART_MESSAGE_ERRCODE (IDX,MTYPE,CODE,DESCRIPTION,REG_DATE) values (102,'N','1000','성공',NOW());


-- 테이블 SMART_MESSAGE의 구조를 덤프합니다. SMART_MESSAGE_SEND
DROP TABLE IF EXISTS `SMART_MESSAGE_SEND`;
CREATE TABLE IF NOT EXISTS `SMART_MESSAGE_SEND` (
  `AIDX` varchar(20) NOT NULL,
  `PRIORITY` varchar(5) DEFAULT NULL,
  `T_REQ` varchar(2) DEFAULT NULL,
  PRIMARY KEY (`AIDX`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.


-- 테이블 SMART_MESSAGE의 구조를 덤프합니다. SMART_MESSAGE_TEMPLATE
DROP TABLE IF EXISTS `SMART_MESSAGE_TEMPLATE`;
CREATE TABLE `SMART_MESSAGE_TEMPLATE` (
  `PIDX` INT(20) NOT NULL AUTO_INCREMENT,
  `AIDX` VARCHAR(20) NULL DEFAULT NULL,
  `CODE` VARCHAR(40) NOT NULL,
  `SUBJECT` VARCHAR(40) NOT NULL,
  `CONTENT` VARCHAR(2000) NOT NULL,
  `REG_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MOD_DATE` timestamp NOT NULL,
  `PRIORITY` VARCHAR(10) NOT NULL,
  `USE_YN` VARCHAR(4) NOT NULL DEFAULT 'N',
  `DELI_NO` VARCHAR(30) NULL DEFAULT NULL,
  `TABLE_DIV` VARCHAR(10) NULL DEFAULT NULL,
  `INFO_YN` VARCHAR(4) NULL DEFAULT NULL,
  `DIV_NM` VARCHAR(50) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(256) NULL DEFAULT NULL,
  `PROCESS` VARCHAR(4) NULL DEFAULT NULL,
  `PROC_AIDX` VARCHAR(20) NULL DEFAULT NULL,
  `USE` VARCHAR(4) NULL DEFAULT 'N',
  `LIMIT_YN` VARCHAR(4) NULL DEFAULT 'N',
  `LIMIT_TYPE` VARCHAR(4) NULL DEFAULT NULL, /* 분: M, 시: H, 일: D */
  `LIMIT_COUNT` INT(6) NULL DEFAULT 0,
  `LIMIT_START_HOUR` INT(6) NULL , /* 발생 시작 시간 */
  `LIMIT_END_HOUR` INT(6) NULL ,/* 발생 종료 시간 */
  PRIMARY KEY (`PIDX`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
AUTO_INCREMENT=1;


-- 내보낼 데이터가 선택되어 있지 않습니다.
DROP TABLE NMS_SEND;

CREATE TABLE NMS_SEND (
  PIDX INT(10) NOT NULL AUTO_INCREMENT COMMENT '인덱스(자동증가값)',
  UKEY VARCHAR(32) NOT NULL COMMENT 'UMS 키값',
  AIDX VARCHAR(20) NOT NULL COMMENT 'AGENT ID',
  MESSAGE VARCHAR(3078) NOT NULL COMMENT '메시지 내용',
  SENDER VARCHAR(15) NOT NULL COMMENT '발신번호(AGENT ID)',
  PHONE VARCHAR(15) NOT NULL COMMENT '수신번호',
  TYPE VARCHAR(4) NULL DEFAULT 'G' COMMENT '메시지 타입 일반(G), 이미지(I)',
  SMS VARCHAR(4) NULL DEFAULT 'N' COMMENT 'SMS발송 요청 DEFUALT N',
  REQ_DATE DATETIME NOT NULL COMMENT '발송 요청일',
  SEND_DATE DATETIME NULL DEFAULT NULL COMMENT '발송 시작시간',
  REPORT_DATE DATETIME NULL DEFAULT NULL COMMENT '수신일',
  STATUS VARCHAR(4) NOT NULL DEFAULT '0' COMMENT '발송상태 발송대기(0), 수신대기(1), 수신완료(2)',
  REQ_RESULT VARCHAR(20) NULL DEFAULT '1' COMMENT '수신결과대기 1',
  PRIMARY KEY (PIDX)
)
COMMENT='AGENT 발송테이블'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;


drop table NMS_SEND_LOG_201604;

CREATE TABLE NMS_SEND_LOG_201604 (
  PIDX INT(10) NOT NULL DEFAULT '0' COMMENT '인덱스(자동증가값)',
  UKEY VARCHAR(32) NOT NULL COMMENT 'UMS 키값',
  AIDX VARCHAR(20) NOT NULL COMMENT 'AGENT ID',
  MESSAGE VARCHAR(3078) NOT NULL COMMENT '메시지 내용',
  SENDER VARCHAR(15) NOT NULL COMMENT '발신번호(AGENT ID)',
  PHONE VARCHAR(15) NOT NULL COMMENT '수신번호',
  TYPE VARCHAR(4) NULL DEFAULT 'G' COMMENT '메시지 타입 일반(G), 이미지(I)',
  SMS VARCHAR(4) NULL DEFAULT 'N' COMMENT 'SMS발송 요청 DEFUALT N',
  REQ_DATE DATETIME NOT NULL COMMENT '발송 요청일',
  SEND_DATE DATETIME NULL DEFAULT NULL COMMENT '발송 시작시간',
  REPORT_DATE DATETIME NULL DEFAULT NULL COMMENT '수신일',
  STATUS VARCHAR(4) NOT NULL DEFAULT '0' COMMENT '발송상태 발송대기(0), 수신대기(1), 수신완료(2)',
  REQ_RESULT VARCHAR(20) NULL DEFAULT '1' COMMENT '수신결과대기 1'
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

-- 테이블 SMART_MESSAGE의 구조를 덤프합니다. SMART_MESSAGE_TEMPLATE_HISTORY
DROP TABLE IF EXISTS `SMART_MESSAGE_TEMPLATE_HISTORY`;
CREATE TABLE `SMART_MESSAGE_TEMPLATE_HISTORY` (
  `PIDX` INT(20) NOT NULL AUTO_INCREMENT,
  `AIDX` VARCHAR(20) NULL DEFAULT NULL,
  `CODE` VARCHAR(40) NOT NULL,
  `SUBJECT` VARCHAR(40) NOT NULL,
  `CONTENT` VARCHAR(2000) NOT NULL,
  `REG_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MOD_DATE` TIMESTAMP NOT NULL ,
  `PRIORITY` VARCHAR(10) NOT NULL,
  `USE_YN` VARCHAR(4) NOT NULL DEFAULT 'N',
  `DELI_NO` VARCHAR(30) NULL DEFAULT NULL,
  `TABLE_DIV` VARCHAR(10) NULL DEFAULT NULL,
  `INFO_YN` VARCHAR(4) NULL DEFAULT NULL,
  `DIV_NM` VARCHAR(50) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(256) NULL DEFAULT NULL,
  `PROCESS` VARCHAR(4) NULL DEFAULT NULL,
  `PROC_AIDX` VARCHAR(20) NULL DEFAULT NULL,
  `STATUS` VARCHAR(4) NULL DEFAULT NULL,
  `USE` VARCHAR(4) NULL DEFAULT NULL,
  `LIMIT_YN` VARCHAR(4) NULL DEFAULT 'N',
  `LIMIT_TYPE` VARCHAR(4) NULL DEFAULT NULL,
  `LIMIT_COUNT` INT(6) NULL DEFAULT 0,
  `LIMIT_START_HOUR` INT(6) NULL , /* 발생 시작 시간 */
  `LIMIT_END_HOUR` INT(6) NULL ,/* 발생 종료 시간 */
  PRIMARY KEY (`PIDX`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
AUTO_INCREMENT=1;


-- 내보낼 데이터가 선택되어 있지 않습니다.


-- 테이블 SMART_MESSAGE의 구조를 덤프합니다. SMART_MESSAGE_TOTAL
DROP TABLE IF EXISTS `SMART_MESSAGE_TOTAL`;
CREATE TABLE IF NOT EXISTS `SMART_MESSAGE_TOTAL` (
  `PIDX` int(20) NOT NULL AUTO_INCREMENT,
  `MTYPE` varchar(4) DEFAULT NULL,
  `AIDX` varchar(20) DEFAULT NULL,
  `UKEY` varchar(32) NOT NULL,
  `MESSAGE` varchar(4000) NOT NULL,
  `SENDER` varchar(200) NOT NULL,
  `RECEIVE_NUM` varchar(200) DEFAULT NULL,
  `REQ_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `RESERVE_DATE` timestamp NULL,
  `SEND_DATE` timestamp NULL,
  `IS_WORK` varchar(4) NOT NULL,
  `CODE` varchar(40) DEFAULT NULL,
  `SRC_TABLE` varchar(30) DEFAULT NULL,
  `FAX_FILE` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`PIDX`),
  KEY `ix_SMART_MESSAGE_TOTAL_01` (`CODE`),
  KEY `ix_SMART_MESSAGE_TOTAL_02` (`IS_WORK`),
  KEY `ix_SMART_MESSAGE_TOTAL_03` (`SEND_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.


-- 테이블 SMART_MESSAGE의 구조를 덤프합니다. SMART_MESSAGE_LOG_YYYYMM
DROP TABLE IF EXISTS `SMART_MESSAGE_LOG_201607`;
CREATE TABLE IF NOT EXISTS `SMART_MESSAGE_LOG_201607` (
  `PIDX` int(20) NOT NULL AUTO_INCREMENT,
  `MTYPE` varchar(4) DEFAULT NULL,
  `AIDX` varchar(20) DEFAULT NULL,
  `UKEY` varchar(100) NOT NULL,
  `MESSAGE` varchar(4000) NOT NULL,
  `SENDER` varchar(200) NOT NULL,
  `RECEIVE_NUM` varchar(200) DEFAULT NULL,
  `REQ_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `RESERVE_DATE` timestamp NULL,
  `REPORT_DATE` timestamp NULL ,
  `SEND_DATE` timestamp NULL,
  `REQ_RESULT` varchar(20) NOT NULL,
  `CODE` varchar(40) NOT NULL,
  `SRC_TABLE` varchar(30) NOT NULL,
  `FAX_FILE` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`PIDX`),
  KEY `ix_smart_message_log_201607_01` (`CODE`,`MTYPE`),
  KEY `ix_SMART_MESSAGE_LOG_201607_02` (`SEND_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



-- 테이블 SMART_MESSAGE의 구조를 덤프합니다. UDS_LOG_201601
DROP TABLE IF EXISTS `UDS_LOG_201601`;
CREATE TABLE IF NOT EXISTS `UDS_LOG_201601` (
  `CMID` varchar(32) DEFAULT NULL,
  `UMID` varchar(32) DEFAULT NULL,
  `MSG_TYPE` int(11) DEFAULT '0',
  `STATUS` int(11) DEFAULT '0',
  `REQUEST_TIME` date NOT NULL,
  `SEND_TIME` date DEFAULT NULL,
  `REPORT_TIME` date DEFAULT NULL,
  `DEST_PHONE` varchar(16) NOT NULL,
  `DEST_NAME` varchar(32) DEFAULT NULL,
  `SEND_PHONE` varchar(16) DEFAULT NULL,
  `SEND_NAME` varchar(32) DEFAULT NULL,
  `SUBJECT` varchar(60) DEFAULT NULL,
  `MSG_BODY` varchar(2000) DEFAULT NULL,
  `WAP_URL` varchar(80) DEFAULT NULL,
  `COVER_FLAG` int(11) DEFAULT '0',
  `SMS_FLAG` int(11) DEFAULT '0',
  `REPLY_FLAG` int(11) DEFAULT '0',
  `RETRY_CNT` int(11) DEFAULT '1',
  `FAX_FILE` varchar(128) DEFAULT NULL,
  `VXML_FILE` varchar(64) DEFAULT NULL,
  `CALL_STATUS` int(11) DEFAULT '9',
  `USE_PAGE` int(11) DEFAULT '0',
  `USE_TIME` int(11) DEFAULT '0',
  `SN_RESULT` int(11) DEFAULT '0',
  `WAP_INFO` varchar(10) DEFAULT '-',
  `CINFO` varchar(32) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.


-- 테이블 SMART_MESSAGE의 구조를 덤프합니다. UDS_LOG_201602
DROP TABLE IF EXISTS `UDS_LOG_201602`;
CREATE TABLE IF NOT EXISTS `UDS_LOG_201602` (
  `CMID` varchar(32) DEFAULT NULL,
  `UMID` varchar(32) DEFAULT NULL,
  `MSG_TYPE` int(11) DEFAULT '0',
  `STATUS` int(11) DEFAULT '0',
  `REQUEST_TIME` date NOT NULL,
  `SEND_TIME` date DEFAULT NULL,
  `REPORT_TIME` date DEFAULT NULL,
  `DEST_PHONE` varchar(16) NOT NULL,
  `DEST_NAME` varchar(32) DEFAULT NULL,
  `SEND_PHONE` varchar(16) DEFAULT NULL,
  `SEND_NAME` varchar(32) DEFAULT NULL,
  `SUBJECT` varchar(60) DEFAULT NULL,
  `MSG_BODY` varchar(2000) DEFAULT NULL,
  `WAP_URL` varchar(80) DEFAULT NULL,
  `COVER_FLAG` int(11) DEFAULT '0',
  `SMS_FLAG` int(11) DEFAULT '0',
  `REPLY_FLAG` int(11) DEFAULT '0',
  `RETRY_CNT` int(11) DEFAULT '1',
  `FAX_FILE` varchar(128) DEFAULT NULL,
  `VXML_FILE` varchar(64) DEFAULT NULL,
  `CALL_STATUS` int(11) DEFAULT '9',
  `USE_PAGE` int(11) DEFAULT '0',
  `USE_TIME` int(11) DEFAULT '0',
  `SN_RESULT` int(11) DEFAULT '0',
  `WAP_INFO` varchar(10) DEFAULT '-',
  `CINFO` varchar(32) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `UDS_LOG_201603`;
CREATE TABLE IF NOT EXISTS `UDS_LOG_201603` (
  `CMID` varchar(32) DEFAULT NULL,
  `UMID` varchar(32) DEFAULT NULL,
  `MSG_TYPE` int(11) DEFAULT '0',
  `STATUS` int(11) DEFAULT '0',
  `REQUEST_TIME` date NOT NULL,
  `SEND_TIME` date DEFAULT NULL,
  `REPORT_TIME` date DEFAULT NULL,
  `DEST_PHONE` varchar(16) NOT NULL,
  `DEST_NAME` varchar(32) DEFAULT NULL,
  `SEND_PHONE` varchar(16) DEFAULT NULL,
  `SEND_NAME` varchar(32) DEFAULT NULL,
  `SUBJECT` varchar(60) DEFAULT NULL,
  `MSG_BODY` varchar(2000) DEFAULT NULL,
  `WAP_URL` varchar(80) DEFAULT NULL,
  `COVER_FLAG` int(11) DEFAULT '0',
  `SMS_FLAG` int(11) DEFAULT '0',
  `REPLY_FLAG` int(11) DEFAULT '0',
  `RETRY_CNT` int(11) DEFAULT '1',
  `FAX_FILE` varchar(128) DEFAULT NULL,
  `VXML_FILE` varchar(64) DEFAULT NULL,
  `CALL_STATUS` int(11) DEFAULT '9',
  `USE_PAGE` int(11) DEFAULT '0',
  `USE_TIME` int(11) DEFAULT '0',
  `SN_RESULT` int(11) DEFAULT '0',
  `WAP_INFO` varchar(10) DEFAULT '-',
  `CINFO` varchar(32) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- 내보낼 데이터가 선택되어 있지 않습니다.


-- 테이블 SMART_MESSAGE의 구조를 덤프합니다. UDS_MSG
DROP TABLE IF EXISTS `UDS_MSG`;
CREATE TABLE IF NOT EXISTS `UDS_MSG` (
  `CMID` varchar(32) DEFAULT NULL,
  `UMID` varchar(32) DEFAULT NULL,
  `MSG_TYPE` int(11) DEFAULT '0',
  `STATUS` int(11) DEFAULT '0',
  `REQUEST_TIME` date NOT NULL,
  `SEND_TIME` date DEFAULT NULL,
  `REPORT_TIME` date DEFAULT NULL,
  `DEST_PHONE` varchar(16) NOT NULL,
  `DEST_NAME` varchar(32) DEFAULT NULL,
  `SEND_PHONE` varchar(16) DEFAULT NULL,
  `SEND_NAME` varchar(32) DEFAULT NULL,
  `SUBJECT` varchar(60) DEFAULT NULL,
  `MSG_BODY` varchar(2000) DEFAULT NULL,
  `WAP_URL` varchar(80) DEFAULT NULL,
  `COVER_FLAG` int(11) DEFAULT '0',
  `SMS_FLAG` int(11) DEFAULT '0',
  `REPLY_FLAG` int(11) DEFAULT '0',
  `RETRY_CNT` int(11) DEFAULT '1',
  `FAX_FILE` varchar(128) DEFAULT NULL,
  `VXML_FILE` varchar(64) DEFAULT NULL,
  `CALL_STATUS` int(11) DEFAULT '9',
  `USE_PAGE` int(11) DEFAULT '0',
  `USE_TIME` int(11) DEFAULT '0',
  `SN_RESULT` int(11) DEFAULT '0',
  `WAP_INFO` varchar(10) DEFAULT '-',
  `CINFO` varchar(32) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;

DROP TABLE IF EXISTS `TBSMS101`;
CREATE TABLE `TBSMS101` (
  `CMID` varchar(32) NOT NULL,
  `UMID` varchar(32) DEFAULT NULL,
  `MSG_TYPE` int(11) DEFAULT '5',
  `STATUS` int(11) DEFAULT '0',
  `REQUEST_TIME` date NOT NULL,
  `SEND_TIME` date DEFAULT NULL,
  `REPORT_TIME` date DEFAULT NULL,
  `DEST_PHONE` varchar(20) NOT NULL,
  `DEST_NAME` varchar(20) DEFAULT NULL,
  `SEND_PHONE` varchar(20) NOT NULL,
  `SEND_NAME` varchar(20) DEFAULT NULL,
  `SUBJECT` varchar(64) DEFAULT NULL,
  `MSG_BODY` varchar(2000) DEFAULT NULL,
  `WAP_URL` varchar(100) DEFAULT NULL,
  `COVER_FLAG` int(11) DEFAULT '0',
  `SMS_FLAG` int(11) DEFAULT '0',
  `REPLY_FLAG` int(11) DEFAULT '0',
  `RETRY_CNT` int(11) DEFAULT '1',
  `FAX_FILE` varchar(1000) DEFAULT NULL,
  `VXML_FILE` varchar(50) DEFAULT NULL,
  `CALL_RESULT` int(11) DEFAULT '9',
  `USE_PAGE` int(11) DEFAULT '0',
  `USE_TIME` int(11) DEFAULT '0',
  `SN_RESULT` int(11) DEFAULT '0',
  `WAP_INFO` varchar(10) DEFAULT '-',
  `CINFO` varchar(32) DEFAULT NULL,
  `ETC1` varchar(50) DEFAULT NULL,
  `ETC2` varchar(50) DEFAULT NULL,
  `ETC3` varchar(50) DEFAULT NULL,
  `ETC4` varchar(50) DEFAULT NULL,
  `ETC5` varchar(50) DEFAULT NULL,
  `MTYPE` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`CMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `TBSMS102`;
CREATE TABLE `TBSMS102` (
  `CMID` varchar(32) NOT NULL,
  `UMID` varchar(32) DEFAULT NULL,
  `MSG_TYPE` int(11) DEFAULT '5',
  `STATUS` int(11) DEFAULT '0',
  `REQUEST_TIME` date NOT NULL,
  `SEND_TIME` date DEFAULT NULL,
  `REPORT_TIME` date DEFAULT NULL,
  `DEST_PHONE` varchar(20) NOT NULL,
  `DEST_NAME` varchar(20) DEFAULT NULL,
  `SEND_PHONE` varchar(20) NOT NULL,
  `SEND_NAME` varchar(20) DEFAULT NULL,
  `SUBJECT` varchar(64) DEFAULT NULL,
  `MSG_BODY` varchar(2000) DEFAULT NULL,
  `WAP_URL` varchar(100) DEFAULT NULL,
  `COVER_FLAG` int(11) DEFAULT '0',
  `SMS_FLAG` int(11) DEFAULT '0',
  `REPLY_FLAG` int(11) DEFAULT '0',
  `RETRY_CNT` int(11) DEFAULT '1',
  `FAX_FILE` varchar(1000) DEFAULT NULL,
  `VXML_FILE` varchar(50) DEFAULT NULL,
  `CALL_RESULT` int(11) DEFAULT '9',
  `USE_PAGE` int(11) DEFAULT '0',
  `USE_TIME` int(11) DEFAULT '0',
  `SN_RESULT` int(11) DEFAULT '0',
  `WAP_INFO` varchar(10) DEFAULT '-',
  `CINFO` varchar(32) DEFAULT NULL,
  `ETC1` varchar(50) DEFAULT NULL,
  `ETC2` varchar(50) DEFAULT NULL,
  `ETC3` varchar(50) DEFAULT NULL,
  `ETC4` varchar(50) DEFAULT NULL,
  `ETC5` varchar(50) DEFAULT NULL,
  `MTYPE` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`CMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `TBSMS103`;
CREATE TABLE `TBSMS103` (
  `CMID` varchar(32) NOT NULL,
  `UMID` varchar(32) DEFAULT NULL,
  `MSG_TYPE` int(11) DEFAULT '5',
  `STATUS` int(11) DEFAULT '0',
  `REQUEST_TIME` date NOT NULL,
  `SEND_TIME` date DEFAULT NULL,
  `REPORT_TIME` date DEFAULT NULL,
  `DEST_PHONE` varchar(20) NOT NULL,
  `DEST_NAME` varchar(20) DEFAULT NULL,
  `SEND_PHONE` varchar(20) NOT NULL,
  `SEND_NAME` varchar(20) DEFAULT NULL,
  `SUBJECT` varchar(64) DEFAULT NULL,
  `MSG_BODY` varchar(2000) DEFAULT NULL,
  `WAP_URL` varchar(100) DEFAULT NULL,
  `COVER_FLAG` int(11) DEFAULT '0',
  `SMS_FLAG` int(11) DEFAULT '0',
  `REPLY_FLAG` int(11) DEFAULT '0',
  `RETRY_CNT` int(11) DEFAULT '1',
  `FAX_FILE` varchar(1000) DEFAULT NULL,
  `VXML_FILE` varchar(50) DEFAULT NULL,
  `CALL_RESULT` int(11) DEFAULT '9',
  `USE_PAGE` int(11) DEFAULT '0',
  `USE_TIME` int(11) DEFAULT '0',
  `SN_RESULT` int(11) DEFAULT '0',
  `WAP_INFO` varchar(10) DEFAULT '-',
  `CINFO` varchar(32) DEFAULT NULL,
  `ETC1` varchar(50) DEFAULT NULL,
  `ETC2` varchar(50) DEFAULT NULL,
  `ETC3` varchar(50) DEFAULT NULL,
  `ETC4` varchar(50) DEFAULT NULL,
  `ETC5` varchar(50) DEFAULT NULL,
  `MTYPE` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`CMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `TBSMS104`;
CREATE TABLE `TBSMS104` (
  `CMID` varchar(32) NOT NULL,
  `UMID` varchar(32) DEFAULT NULL,
  `MSG_TYPE` int(11) DEFAULT '5',
  `STATUS` int(11) DEFAULT '0',
  `REQUEST_TIME` date NOT NULL,
  `SEND_TIME` date DEFAULT NULL,
  `REPORT_TIME` date DEFAULT NULL,
  `DEST_PHONE` varchar(20) NOT NULL,
  `DEST_NAME` varchar(20) DEFAULT NULL,
  `SEND_PHONE` varchar(20) NOT NULL,
  `SEND_NAME` varchar(20) DEFAULT NULL,
  `SUBJECT` varchar(64) DEFAULT NULL,
  `MSG_BODY` varchar(2000) DEFAULT NULL,
  `WAP_URL` varchar(100) DEFAULT NULL,
  `COVER_FLAG` int(11) DEFAULT '0',
  `SMS_FLAG` int(11) DEFAULT '0',
  `REPLY_FLAG` int(11) DEFAULT '0',
  `RETRY_CNT` int(11) DEFAULT '1',
  `FAX_FILE` varchar(1000) DEFAULT NULL,
  `VXML_FILE` varchar(50) DEFAULT NULL,
  `CALL_RESULT` int(11) DEFAULT '9',
  `USE_PAGE` int(11) DEFAULT '0',
  `USE_TIME` int(11) DEFAULT '0',
  `SN_RESULT` int(11) DEFAULT '0',
  `WAP_INFO` varchar(10) DEFAULT '-',
  `CINFO` varchar(32) DEFAULT NULL,
  `ETC1` varchar(50) DEFAULT NULL,
  `ETC2` varchar(50) DEFAULT NULL,
  `ETC3` varchar(50) DEFAULT NULL,
  `ETC4` varchar(50) DEFAULT NULL,
  `ETC5` varchar(50) DEFAULT NULL,
  `MTYPE` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`CMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `TBSMS006`;
CREATE TABLE `TBSMS006` (
  `CMP_MSG_ID` varchar(20) NOT NULL,
  `CMP_USR_ID` varchar(5) NOT NULL,
  `ODR_FG` varchar(1) NOT NULL DEFAULT '2',
  `SMS_GB` varchar(1) NOT NULL DEFAULT '1',
  `USED_CD` varchar(3) NOT NULL DEFAULT '00',
  `MSG_GB` varchar(1) NOT NULL,
  `WRT_DTTM` varchar(14) NOT NULL,
  `SND_DTTM` varchar(14) NOT NULL,
  `SND_PHN_ID` varchar(20) DEFAULT NULL,
  `RCV_PHN_ID` varchar(20) NOT NULL,
  `CALLBACK` varchar(20) DEFAULT NULL,
  `SND_MSG` varchar(200) NOT NULL,
  `CMP_SND_DTTM` varchar(14) DEFAULT NULL,
  `CMP_RCV_DTTM` varchar(14) DEFAULT NULL,
  `REG_SND_DTTM` varchar(14) DEFAULT NULL,
  `REG_RCV_DTTM` varchar(14) DEFAULT NULL,
  `EXPIRE_VAL` int(11) NOT NULL DEFAULT '0',
  `SMS_ST` varchar(1) NOT NULL,
  `RSLT_VAL` int(11) NOT NULL DEFAULT '99',
  `RSRVD_ID` varchar(20) DEFAULT NULL,
  `RSRVD_WD` varchar(35) DEFAULT NULL,
  `ETC1` varchar(100) DEFAULT NULL,
  `ETC2` varchar(100) DEFAULT NULL,
  `ETC3` varchar(100) DEFAULT NULL,
  `ETC4` varchar(100) DEFAULT NULL,
  `ETC5` varchar(100) DEFAULT NULL,
  `MTYPE` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`CMP_MSG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `TBSMS007`;
CREATE TABLE `TBSMS007` (
  `CMP_MSG_ID` varchar(20) NOT NULL,
  `CMP_USR_ID` varchar(5) NOT NULL,
  `ODR_FG` varchar(1) NOT NULL DEFAULT '2',
  `SMS_GB` varchar(1) NOT NULL DEFAULT '1',
  `USED_CD` varchar(3) NOT NULL DEFAULT '00',
  `MSG_GB` varchar(1) NOT NULL,
  `WRT_DTTM` varchar(14) NOT NULL,
  `SND_DTTM` varchar(14) NOT NULL,
  `SND_PHN_ID` varchar(20) DEFAULT NULL,
  `RCV_PHN_ID` varchar(20) NOT NULL,
  `CALLBACK` varchar(20) DEFAULT NULL,
  `SND_MSG` varchar(200) NOT NULL,
  `CMP_SND_DTTM` varchar(14) DEFAULT NULL,
  `CMP_RCV_DTTM` varchar(14) DEFAULT NULL,
  `REG_SND_DTTM` varchar(14) DEFAULT NULL,
  `REG_RCV_DTTM` varchar(14) DEFAULT NULL,
  `EXPIRE_VAL` int(11) NOT NULL DEFAULT '0',
  `SMS_ST` varchar(1) NOT NULL,
  `RSLT_VAL` int(11) NOT NULL DEFAULT '99',
  `RSRVD_ID` varchar(20) DEFAULT NULL,
  `RSRVD_WD` varchar(35) DEFAULT NULL,
  `ETC1` varchar(100) DEFAULT NULL,
  `ETC2` varchar(100) DEFAULT NULL,
  `ETC3` varchar(100) DEFAULT NULL,
  `ETC4` varchar(100) DEFAULT NULL,
  `ETC5` varchar(100) DEFAULT NULL,
  `MTYPE` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`CMP_MSG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- SMS 메시지 발송 테이블

DROP TABLE TBLMESSAGE;

CREATE TABLE TBLMESSAGE 
(
	  FSERIAL INT PRIMARY KEY NOT NULL 
	, FUSERID VARCHAR(16)
	, FSENDDATE DATE 
	, FSENDSTAT VARCHAR(1) DEFAULT '0' NOT NULL 
	, FRSLTSTAT VARCHAR(2) DEFAULT '00' 
	, FMSGTYPE VARCHAR(1) DEFAULT '0' 
	, FDESTINE VARCHAR(20) NOT NULL 
	, FCALLBACK VARCHAR(20) 
	, FRSLTDATE DATE 
	, FMODIDATE DATE 
	, FTEXT VARCHAR(160) 
	, FETC VARCHAR(160)
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS SMS_LOG_201603;

CREATE TABLE SMS_LOG_201603 
(
	  FSERIAL INT PRIMARY KEY NOT NULL 
	, FUSERID VARCHAR(16)
	, FSENDDATE DATE 
	, FSENDSTAT VARCHAR(1) DEFAULT '0' NOT NULL 
	, FRSLTSTAT VARCHAR(2) DEFAULT '00' 
	, FMSGTYPE VARCHAR(1) DEFAULT '0' 
	, FDESTINE VARCHAR(20) NOT NULL 
	, FCALLBACK VARCHAR(20) 
	, FRSLTDATE DATE 
	, FMODIDATE DATE 
	, FTEXT VARCHAR(160) 
	, FETC VARCHAR(160)
);

-- 수신거부 리스트
DROP TABLE IF EXISTS SMART_MESSAGE_BANLIST;

CREATE TABLE SMART_MESSAGE_BANLIST 
(	
	`PIDX` INT PRIMARY KEY AUTO_INCREMENT, 
	`MTYPE` VARCHAR(4), 
	`REFUSE` VARCHAR(4), 
	`RECEIVE_NUM` VARCHAR(20), 
	`SRC_TABLE` VARCHAR(20), 
	`SRC_DESC` VARCHAR(100), 
	`REG_DATE` DATE, 
	`MOD_DATE` DATE, 
	`DEL_DESC` VARCHAR(200), 
	`STATUS` VARCHAR(4), 
	`AIDX` VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS SMART_MESSAGE_BANLIST_HISTORY;
CREATE TABLE SMART_MESSAGE_BANLIST_HISTORY
(	
	`PIDX` INT PRIMARY KEY AUTO_INCREMENT, 
	`MTYPE` VARCHAR(4), 
	`REFUSE` VARCHAR(4), 
	`RECEIVE_NUM` VARCHAR(20), 
	`SRC_TABLE` VARCHAR(20), 
	`SRC_DESC` VARCHAR(100), 
	`REG_DATE` DATE, 
	`MOD_DATE` DATE, 
	`DEL_DESC` VARCHAR(200), 
	`STATUS` VARCHAR(4), 
	`AIDX` VARCHAR(20) NOT NULL
);



INSERT INTO `SMART_AGENT_INFO` (`AIDX`, `NAME`, `PASSWD`, `PHONE`, `CIDX`, `AUTH`, `REG_DATE`)
VALUES
  ('smart', '관리자', 'KZ4f46ITRo6xeqSmyOB6/Q==', '01000000000', 'tfgw', 'M', '2016-02-24 05:45:53');
  /* smart/smart1234 */

  
  
  
  
  DROP TABLE IF EXISTS  NMS_SEND;
  CREATE TABLE `NMS_SEND` (
	`PIDX` INT(10) NOT NULL AUTO_INCREMENT COMMENT '인덱스(자동증가값)',
	`UKEY` VARCHAR(32) NOT NULL COMMENT 'UMS 키값',
	`AIDX` VARCHAR(20) NOT NULL COMMENT 'AGENT ID',
	`MESSAGE` VARCHAR(3078) NOT NULL COMMENT '메시지 내용',
	`SENDER` VARCHAR(15) NOT NULL COMMENT '발신번호(AGENT ID)',
	`PHONE` VARCHAR(15) NOT NULL COMMENT '수신번호',
	`TYPE` VARCHAR(4) NULL DEFAULT 'G' COMMENT '메시지 타입 일반(G), 이미지(I)',
	`SMS` VARCHAR(4) NULL DEFAULT 'N' COMMENT 'SMS발송 요청 DEFUALT N',
	`REQ_DATE` DATETIME NOT NULL COMMENT '발송 요청일',
	`SEND_DATE` DATETIME NULL DEFAULT NULL COMMENT '발송 시작시간',
	`REPORT_DATE` DATETIME NULL DEFAULT NULL COMMENT '수신일',
	`STATUS` VARCHAR(4) NOT NULL DEFAULT '0' COMMENT '발송상태 발송대기(0), 수신대기(1), 수신완료(2)',
	`REQ_RESULT` VARCHAR(20) NULL DEFAULT '1' COMMENT '수신결과대기 1',
	PRIMARY KEY (`PIDX`)
)
COMMENT='AGENT 발송테이블'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;


 DROP TABLE IF EXISTS  NMS_SEND_LOG_201604;
 
CREATE TABLE `NMS_SEND_LOG_201604` (
	`PIDX` INT(10) NOT NULL DEFAULT '0' COMMENT '인덱스(자동증가값)',
	`UKEY` VARCHAR(32) NOT NULL COMMENT 'UMS 키값',
	`AIDX` VARCHAR(20) NOT NULL COMMENT 'AGENT ID',
	`MESSAGE` VARCHAR(3078) NOT NULL COMMENT '메시지 내용',
	`SENDER` VARCHAR(15) NOT NULL COMMENT '발신번호(AGENT ID)',
	`PHONE` VARCHAR(15) NOT NULL COMMENT '수신번호',
	`TYPE` VARCHAR(4) NULL DEFAULT 'G' COMMENT '메시지 타입 일반(G), 이미지(I)',
	`SMS` VARCHAR(4) NULL DEFAULT 'N' COMMENT 'SMS발송 요청 DEFUALT N',
	`REQ_DATE` DATETIME NOT NULL COMMENT '발송 요청일',
	`SEND_DATE` DATETIME NULL DEFAULT NULL COMMENT '발송 시작시간',
	`REPORT_DATE` DATETIME NULL DEFAULT NULL COMMENT '수신일',
	`STATUS` VARCHAR(4) NOT NULL DEFAULT '0' COMMENT '발송상태 발송대기(0), 수신대기(1), 수신완료(2)',
	`REQ_RESULT` VARCHAR(20) NULL DEFAULT '1' COMMENT '수신결과대기 1'
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

  
  INSERT INTO `SMART_MESSAGE_TEMPLATE` (`AIDX`, `CODE`, `SUBJECT`, `CONTENT`, `REG_DATE`, `MOD_DATE`, `PRIORITY`, `USE_YN`, `DELI_NO`, `TABLE_DIV`, `INFO_YN`, `DIV_NM`, `DESCRIPTION`, `PROCESS`, `PROC_AIDX`, `USE`, `LIMIT_YN`, `LIMIT_TYPE`, `LIMIT_COUNT`)
VALUES
	( 'smart', 'Z999', 'Z999', '#', '2016-03-28 11:07:31', '2016-03-28 10:41:10', 'S', 'N', 'Z999', 'R', 'N', '', '', 'S', 'smart', 'Y', NULL, NULL, 1),
	( 'smart', 'TF000001', 'TF000001', '# 발송테스트 건입니다.', '2016-03-28 13:34:27', '2016-03-28 13:34:27', 'S', 'N', 'TF000001', 'R', 'N', '', '', 'S', 'smart', 'Y', 'Y', 'D', 1);

CREATE TABLE `SMART_MESSAGE_smarttest` (
  `CMID` varchar(32) NOT NULL,
  `UMID` varchar(32) DEFAULT NULL,
  `MSG_TYPE` int(11) DEFAULT '0',
  `STATUS` int(11) DEFAULT '0',
  `REQUEST_TIME` date NOT NULL,
  `SEND_TIME` date DEFAULT NULL,
  `REPORT_TIME` date DEFAULT NULL,
  `DEST_PHONE` varchar(16) NOT NULL,
  `DEST_NAME` varchar(32) DEFAULT NULL,
  `SEND_PHONE` varchar(16) DEFAULT NULL,
  `SEND_NAME` varchar(32) DEFAULT NULL,
  `SEND_TYPE` int(11) DEFAULT '0',
  `SUBJECT` varchar(60) DEFAULT NULL,
  `MSG_BODY` varchar(2000) DEFAULT NULL,
  `WAP_URL` varchar(80) DEFAULT NULL,
  `COVER_FLAG` int(11) DEFAULT '0',
  `SMS_FLAG` int(11) DEFAULT '0',
  `REPLY_FLAG` int(11) DEFAULT '0',
  `RETRY_CNT` int(11) DEFAULT '1',
  `FAX_FILE` varchar(128) DEFAULT NULL,
  `VXML_FILE` varchar(64) DEFAULT NULL,
  `CALL_STATUS` int(11) DEFAULT '9',
  `USE_PAGE` int(11) DEFAULT '0',
  `USE_TIME` int(11) DEFAULT '0',
  `SN_RESULT` varchar(10) DEFAULT NULL,
  `WAP_INFO` varchar(10) DEFAULT '-',
  `CINFO` varchar(32) DEFAULT NULL,
  `SRC_TABLE` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`CMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SMART_MESSAGE_smarttest_LOG_201604` (
  `CMID` varchar(32) NOT NULL,
  `UMID` varchar(32) DEFAULT NULL,
  `MSG_TYPE` int(11) DEFAULT '0',
  `STATUS` int(11) DEFAULT '0',
  `REQUEST_TIME` date NOT NULL,
  `SEND_TIME` date DEFAULT NULL,
  `REPORT_TIME` date DEFAULT NULL,
  `DEST_PHONE` varchar(16) NOT NULL,
  `DEST_NAME` varchar(32) DEFAULT NULL,
  `SEND_PHONE` varchar(16) DEFAULT NULL,
  `SEND_NAME` varchar(32) DEFAULT NULL,
  `SEND_TYPE` int(11) DEFAULT '0',
  `SUBJECT` varchar(60) DEFAULT NULL,
  `MSG_BODY` varchar(2000) DEFAULT NULL,
  `WAP_URL` varchar(80) DEFAULT NULL,
  `COVER_FLAG` int(11) DEFAULT '0',
  `SMS_FLAG` int(11) DEFAULT '0',
  `REPLY_FLAG` int(11) DEFAULT '0',
  `RETRY_CNT` int(11) DEFAULT '1',
  `FAX_FILE` varchar(128) DEFAULT NULL,
  `VXML_FILE` varchar(64) DEFAULT NULL,
  `CALL_STATUS` int(11) DEFAULT '9',
  `USE_PAGE` int(11) DEFAULT '0',
  `USE_TIME` int(11) DEFAULT '0',
  `SN_RESULT` varchar(10) DEFAULT NULL,
  `WAP_INFO` varchar(10) DEFAULT '-',
  `CINFO` varchar(32) DEFAULT NULL,
  `SRC_TABLE` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`CMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--cgKang add
DROP TABLE IF EXISTS `SMART_MESSAGE`;
CREATE TABLE `SMART_MESSAGE` (
  `CMID` varchar(32) NOT NULL,
  `UMID` varchar(32) DEFAULT NULL,
  `MSG_TYPE` int(11) DEFAULT '0',
  `STATUS` int(11) DEFAULT '0',
  `REQUEST_TIME` date NOT NULL,
  `SEND_TIME` date DEFAULT NULL,
  `REPORT_TIME` date DEFAULT NULL,
  `DEST_PHONE` varchar(16) NOT NULL,
  `DEST_NAME` varchar(32) DEFAULT NULL,
  `SEND_PHONE` varchar(16) DEFAULT NULL,
  `SEND_NAME` varchar(32) DEFAULT NULL,
  `SEND_TYPE` int(11) DEFAULT '0',
  `SUBJECT` varchar(60) DEFAULT NULL,
  `MSG_BODY` varchar(2000) DEFAULT NULL,
  `WAP_URL` varchar(80) DEFAULT NULL,
  `COVER_FLAG` int(11) DEFAULT '0',
  `SMS_FLAG` int(11) DEFAULT '0',
  `REPLY_FLAG` int(11) DEFAULT '0',
  `RETRY_CNT` int(11) DEFAULT '1',
  `FAX_FILE` varchar(128) DEFAULT NULL,
  `VXML_FILE` varchar(64) DEFAULT NULL,
  `CALL_STATUS` int(11) DEFAULT '9',
  `USE_PAGE` int(11) DEFAULT '0',
  `USE_TIME` int(11) DEFAULT '0',
  `SN_RESULT` varchar(10) DEFAULT NULL,
  `WAP_INFO` varchar(10) DEFAULT '-',
  `CINFO` varchar(32) DEFAULT NULL,
  `LONG_LINK` varchar(500) DEFAULT NULL,
  `SHORT_LINK` varchar(500) DEFAULT NULL,
  `LINK_AUTH` varchar(30) DEFAULT NULL,
  `LINK_LIMIT` int(11) DEFAULT NULL,
  `LINK_CNT` int(11) DEFAULT NULL,
  PRIMARY KEY (`CMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8


--[Client DB table]
-- alter table SMART_MESSAGE add LONG_LINK varchar(500) DEFAULT NULL;   -- long link
-- alter table SMART_MESSAGE add SHORT_LINK varchar(500) DEFAULT NULL;  -- short link
-- alter table SMART_MESSAGE add LINK_LIMIT int(11) DEFAULT NULL;  		-- 발송기한 (일 기준)
-- alter table SMART_MESSAGE add LINK_CNT int(11) DEFAULT NULL;  		-- 클릭 (접근 횟수)
-- alter table SMART_MESSAGE add LINK_AUTH varchar(30) DEFAULT NULL;  	-- 인증정보 (주민번호)

--[Server DB table]
-- alter table SMART_MESSAGE_smarttest add LONG_LINK varchar(500) DEFAULT NULL;   	-- long link
-- alter table SMART_MESSAGE_smarttest add SHORT_LINK varchar(500) DEFAULT NULL;  	-- short link
-- alter table SMART_MESSAGE_smarttest add LINK_LIMIT int(11) DEFAULT NULL;  		-- 발송기한 (일 기준)
-- alter table SMART_MESSAGE_smarttest add LINK_CNT int(11) DEFAULT NULL;  			-- 클릭 (접근 횟수)
-- alter table SMART_MESSAGE_smarttest add LINK_AUTH varchar(30) DEFAULT NULL;  	-- 인증정보 (주민번호)
-- 로그 테이블 DB 도 동일하게 작업

  